export default [
  // {
  //   label: "通用图标",
  //   list: [
  //     "iconfont iconicon_roundadd",
  //     "iconfont iconicon_compile",
  //     "iconfont iconicon_glass",
  //     "iconfont iconicon_roundclose",
  //     "iconfont iconicon_roundreduce",
  //     "iconfont iconicon_delete",
  //     "iconfont iconicon_shakehands",
  //     "iconfont iconicon_task_done",
  //     "iconfont iconicon_voipphone",
  //     "iconfont iconicon_safety",
  //     "iconfont iconicon_work",
  //     "iconfont iconicon_study",
  //     "iconfont iconicon_task",
  //     "iconfont iconicon_subordinate",
  //     "iconfont iconicon_star",
  //     "iconfont iconicon_setting",
  //     "iconfont iconicon_sms",
  //     "iconfont iconicon_share",
  //     "iconfont iconicon_secret",
  //     "iconfont iconicon_scan_namecard",
  //     "iconfont iconicon_principal",
  //     "iconfont iconicon_group",
  //     "iconfont iconicon_send",
  //     "iconfont iconicon_scan",
  //     "iconfont iconicon_search",
  //     "iconfont iconicon_refresh",
  //     "iconfont iconicon_savememo",
  //     "iconfont iconicon_QRcode",
  //     "iconfont iconicon_im_keyboard",
  //     "iconfont iconicon_redpacket",
  //     "iconfont iconicon_photo",
  //     "iconfont iconicon_qq",
  //     "iconfont iconicon_wechat",
  //     "iconfont iconicon_phone",
  //     "iconfont iconicon_namecard",
  //     "iconfont iconicon_notice",
  //     "iconfont iconicon_next_arrow",
  //     "iconfont iconicon_left",
  //     "iconfont iconicon_more",
  //     "iconfont iconicon_details",
  //     "iconfont iconicon_message",
  //     "iconfont iconicon_mobilephone",
  //     "iconfont iconicon_im_voice",
  //     "iconfont iconicon_GPS",
  //     "iconfont iconicon_ding",
  //     "iconfont iconicon_exchange",
  //     "iconfont iconicon_cspace",
  //     "iconfont iconicon_doc",
  //     "iconfont iconicon_dispose",
  //     "iconfont iconicon_discovery",
  //     "iconfont iconicon_community_line",
  //     "iconfont iconicon_cloud_history",
  //     "iconfont iconicon_coinpurse_line",
  //     "iconfont iconicon_airplay",
  //     "iconfont iconicon_at",
  //     "iconfont iconicon_addressbook",
  //     "iconfont iconicon_boss",
  //     "iconfont iconicon_addperson",
  //     "iconfont iconicon_affiliations_li",
  //     "iconfont iconicon_addmessage",
  //     "iconfont iconicon_addresslist",
  //     "iconfont iconicon_add",
  //     "iconfont icongithub",
  //     "iconfont icongitee2",
  //   ]
  // },
  {
    label: "系统图标",
    list: [
      "iconfont icon-zhongyingwen",
      "iconfont icon-caidan",
      "iconfont icon-rizhi1",
      "iconfont icon-zhuti",
      "iconfont icon-suoping",
      "iconfont icon-bug",
      "iconfont icon-qq1",
      "iconfont icon-weixin1",
      "iconfont icon-shouji",
      "iconfont icon-mima",
      "iconfont icon-yonghu",
      "iconfont icon-yanzhengma",
      "iconfont icon-canshu",
      "iconfont icon-dongtai",
      "iconfont icon-iconset0265",
      "iconfont icon-shujuzhanshi2",
      "iconfont icon-tuichuquanping",
      "iconfont icon-rizhi",
      "iconfont icon-cuowutishitubiao",
      "iconfont icon-debug",
      "iconfont icon-iconset0216",
      "iconfont icon-quanxian",
      "iconfont icon-quanxian",
      "iconfont icon-shuaxin",
      "iconfont icon-bofangqi-suoping",
      "iconfont icon-quanping",
      "iconfont icon-navicon",
      "iconfont icon-biaodan",
      "iconfont icon-liuliangyunpingtaitubiao08",
      "iconfont icon-caidanguanli",
      "iconfont icon-cuowu",
      "iconfont icon-wxbgongju",
      "iconfont icon-tuichu",
      "iconfont icon-daohanglanmoshi02",
      "iconfont icon-changyonglogo27",
      "iconfont icon-biaoge",
      "iconfont icon-baidu1",
      "iconfont icon-tubiao",
      "iconfont icon-souhu",
      "iconfont icon-msnui-360",
      "iconfont icon-iframe",
      "iconfont icon-huanyingye",
    ]
  }, {
    label: '自定义图标',
    list: [
      "iconfont icontuichu",
      "iconfont iconduihao2",
      "iconfont iconriqi",
      "iconfont iconrenwu",
      "iconfont iconyuyin",
      "iconfont icontianjia",
      "iconfont icon_zhanbi",
      "iconfont iconbaojingzhuangtaiqidong-05",
      "iconfont iconjinrilichang",
      "iconfont iconzuobiao",
      "iconfont iconrenyuan-05",
      "iconfont iconqixiangjiance",
      "iconfont icondingwei3",
      "iconfont iconwu",
      "iconfont iconzaizhirenyuan",
      "iconfont iconguanliyuan",
      "iconfont iconzongrenshu",
      "iconfont iconleibie",
      "iconfont iconrenyuanlikai",
      "iconfont iconzuzhi",
      "iconfont icona-ziyuan3",
      "iconfont iconzaoyin",
      "iconfont iconshidu",
      "iconfont iconapp_icons--1",
      "iconfont iconapp_icons--2",
      "iconfont iconwind-direction",
      "iconfont iconfengsu2",
      "iconfont iconfuchen",
      "iconfont iconwendu",
      "iconfont iconshijian2",
      "iconfont icontongzhi1",
      "iconfont iconlizhi",
      "iconfont iconiconset0230",
      "iconfont iconjiugongge",
      "iconfont iconquanxiaozongrenshu",
      "iconfont iconquanbu",
      "iconfont iconqingjiaowuxianqingjiao",
      "iconfont iconshangchuan",
      "iconfont iconcolum-height",
      "iconfont iconzu597",
      "iconfont iconbaojing1",
      "iconfont iconshijian1",
      "iconfont icontongzhi",
      "iconfont iconxianshi",
      "iconfont iconxinzengtubiao-24",
      "iconfont iconjinri",
      "iconfont iconhuizongshuju",
      "iconfont iconpingjunmeiri",
      "iconfont iconsuoli",
      "iconfont iconzhangfu",
      "iconfont iconshebeileixing",
      "iconfont iconhekriconjiashi",
      "iconfont icongaodu",
      "iconfont icontubiao-chushuang",
      "iconfont iconshijian",
      "iconfont iconsiji-",
      "iconfont iconfengji",
      "iconfont iconjiare",
      "iconfont iconfengsu1",
      "iconfont iconzhiding",
      "iconfont iconapp_icons--",
      "iconfont iconIOTtubiao_huabanfuben",
      "iconfont iconspeed_line",
      "iconfont iconcanshuiconyouhua-",
      "iconfont icongaochengweiyi",
      "iconfont iconbj",
      "iconfont iconhrcollegepeopleCardingRange",
      "iconfont iconicon_yali_dingkong-01",
      "iconfont iconqingjiaochuanganqi",
      "iconfont iconmianxingdiaogouta",
      "iconfont iconlixianshebei",
      "iconfont iconzhileng",
      "iconfont iconzaixianshebei_1",
      "iconfont iconchushi",
      "iconfont iconerjiyasuojichuanganqiguzhang",
      "iconfont iconbaojing",
      "iconfont iconqixiangzhan",
      "iconfont iconqixiangzhan1",
      "iconfont icondian",
      "iconfont iconshuijinbaojing",
      "iconfont iconpenling",
      "iconfont iconshachenbao",
      "iconfont icondingwei2",
      "iconfont iconc_blue",
      "iconfont iconc_green",
      "iconfont icontadiao-",
      "iconfont iconshipin-",
      "iconfont iconshengjiangti-",
      "iconfont iconjizhanfugai",
      "iconfont iconlouceng1",
      "iconfont icondianziweilan1",
      "iconfont iconzhajimenjin",
      "iconfont iconshexiangtou",
      "iconfont iconshexiangtou-copy",
      "iconfont iconjhu_yunshangchuan",
      "iconfont iconjinhu_yunxiazai",
      "iconfont iconiconfont_download",
      "iconfont iconiconfont_yunshangchuan",
      "iconfont icondingwei",
      "iconfont iconyangchen",
      "iconfont iconyewurenyuanxinxiguanli",
      "iconfont icontupian",
      "iconfont iconleijinshucailiaox",
      "iconfont iconjinhu_xfdt",
      "iconfont iconkaoqin",
      "iconfont iconshigongrenyuan ",
      "iconfont iconicon-Important-H",
      "iconfont iconjiangli",
      "iconfont  iconanquan",
      "iconfont iconGroup- ",
      "iconfont iconfengshan",
      "iconfont iconmoxingcanshu_ ",
      "iconfont  iconshebeiguanli",
      "iconfont  iconmoxingliulan",
      "iconfont iconjinhu_shengchandacheng-",
      "iconfont iconpenlin ",
      "iconfont iconziyuan ",
      "iconfont iconpenlin1 ",
      "iconfont iconkaoqinshenpi ",
      "iconfont icongfjianzhuwu ",
      "iconfont iconicon-test ",
      "iconfont iconrenyuanguanli ",
      "iconfont  icontupian1",
      "iconfont iconpeitaosheshixiaotubiao_dianti ",
      "iconfont iconjinhu_shebeiManage ",
      "iconfont iconfengsu ",
      "iconfont  iconanquanzhuye",
      "iconfont iconrenyuanxinxiguanli ",
      "iconfont iconwenshidu ",
      "iconfont iconshangchuanmoxing ",
      "iconfont iconrenlianshibie ",
      "iconfont  icon009jianzhuwu",
      "iconfont icondingwei1 ",
      "iconfont  iconrenliangshibie",
      "iconfont  icondianti",
      "iconfont  iconfenglifadian",
      "iconfont iconanquan1 ",
      "iconfont iconjinhu_anquanhuiyi ",
      "iconfont  iconwenshidu1",
      "iconfont  iconshigongchuli",
      "iconfont  icontadiao",
      "iconfont  iconyangchen1",
      "iconfont  icongaozhimo",
      "iconfont  iconshuidianbiao",
      "iconfont  iconcongyerenyuanguanli",
      "iconfont iconcailiaoguanli ",
      "iconfont iconjinhu_sgjhqingdan ",
      "iconfont iconicon-yongjiujiancai",
      "iconfont icontezhengwendu ",
      "iconfont iconwenshidu2 ",
      "iconfont iconrenyuanguanli1",
      "iconfont iconfont_download",
      "iconfont iconjinhu_yunxiazai",
      "iconfont iconjhu_yunshangchuan"

    ]
  }
]
